from __future__ import annotations

from dataclasses import dataclass
from importlib.util import find_spec
from math import isfinite, log10
from typing import Optional, Tuple


@dataclass(frozen=True)
class AcousticInducedVibrationResult:
    pressure_drop_ratio: float
    sound_power_level_db: float
    diameter_thickness_ratio: float
    allowable_sound_power_level_db: float
    likelihood_of_failure: float
    downstream_pipe_length_m: float
    risk_warning: str
    neqsim_available: bool
    assumptions: Tuple[str, ...]


class AcousticInducedVibrationModel:
    """Educational acoustic-induced-vibration (AIV) screening (Energy Institute style).

    Estimates the sound power level generated by a gas pressure-reducing device
    (control valve, relief valve, or restriction orifice), the pipe
    diameter-to-thickness ratio, an allowable sound power level, and a
    likelihood-of-failure (LOF) index using the public Energy Institute AIV
    screening form. Screening only.
    """

    def __init__(
        self,
        *,
        pwl_constant_db: float = 126.1,
        pwl_reference_db: float = 187.0,
        pwl_dt_slope_db: float = 0.5,
        lof_spread_db: float = 10.0,
    ) -> None:
        self._require_positive("pwl_constant_db", pwl_constant_db)
        self._require_positive("pwl_reference_db", pwl_reference_db)
        self._require_positive("pwl_dt_slope_db", pwl_dt_slope_db)
        self._require_positive("lof_spread_db", lof_spread_db)
        self.pwl_constant_db = pwl_constant_db
        self.pwl_reference_db = pwl_reference_db
        self.pwl_dt_slope_db = pwl_dt_slope_db
        self.lof_spread_db = lof_spread_db

    def evaluate(
        self,
        *,
        mass_flow_kg_s: float,
        upstream_pressure_bar: float,
        downstream_pressure_bar: float,
        pipe_outside_diameter_mm: float,
        wall_thickness_mm: float,
        molecular_weight: float = 19.0,
        temperature_k: float = 313.15,
        downstream_pipe_length_m: float = 10.0,
        sound_power_level_db: Optional[float] = None,
    ) -> AcousticInducedVibrationResult:
        self._require_positive("mass_flow_kg_s", mass_flow_kg_s)
        self._require_positive("upstream_pressure_bar", upstream_pressure_bar)
        self._require_positive("downstream_pressure_bar", downstream_pressure_bar)
        if downstream_pressure_bar >= upstream_pressure_bar:
            raise ValueError(
                "downstream_pressure_bar must be less than upstream_pressure_bar"
            )
        self._require_positive("pipe_outside_diameter_mm", pipe_outside_diameter_mm)
        self._require_positive("wall_thickness_mm", wall_thickness_mm)
        if pipe_outside_diameter_mm <= 2.0 * wall_thickness_mm:
            raise ValueError(
                "pipe_outside_diameter_mm must be greater than twice wall_thickness_mm"
            )
        self._require_positive("molecular_weight", molecular_weight)
        self._require_positive("temperature_k", temperature_k)
        self._require_positive("downstream_pipe_length_m", downstream_pipe_length_m)
        if sound_power_level_db is not None:
            self._require_positive("sound_power_level_db", sound_power_level_db)

        delta_p = upstream_pressure_bar - downstream_pressure_bar
        pressure_drop_ratio = delta_p / upstream_pressure_bar

        # Energy Institute / Carucci-Mueller screening sound power level.
        # PWL = 10 log10[(dP/P1)^3.6 * mdot^2 * (T/MW)^1.2] + constant.
        if sound_power_level_db is None:
            inner = (
                pressure_drop_ratio ** 3.6
                * mass_flow_kg_s ** 2.0
                * (temperature_k / molecular_weight) ** 1.2
            )
            pwl = 10.0 * log10(inner) + self.pwl_constant_db
        else:
            pwl = sound_power_level_db

        dt_ratio = pipe_outside_diameter_mm / wall_thickness_mm

        # Allowable PWL decreases as the diameter-to-thickness ratio increases.
        allowable_pwl = self.pwl_reference_db - self.pwl_dt_slope_db * dt_ratio

        # LOF index normalised so the allowable PWL maps to LOF = 1.0.
        lof = 1.0 + (pwl - allowable_pwl) / self.lof_spread_db
        lof = max(lof, 0.0)

        risk_warning = self._risk_warning(lof)

        return AcousticInducedVibrationResult(
            pressure_drop_ratio=round(pressure_drop_ratio, 4),
            sound_power_level_db=round(pwl, 3),
            diameter_thickness_ratio=round(dt_ratio, 3),
            allowable_sound_power_level_db=round(allowable_pwl, 3),
            likelihood_of_failure=round(lof, 4),
            downstream_pipe_length_m=round(downstream_pipe_length_m, 3),
            risk_warning=risk_warning,
            neqsim_available=find_spec("neqsim") is not None,
            assumptions=(
                "Educational screening placeholder only (Energy Institute AIV style).",
                "PWL = 10 log10[(dP/P1)^3.6 mdot^2 (T/MW)^1.2] + constant.",
                "Allowable PWL = reference - slope * (D/t); higher D/t lowers the limit.",
                "LOF = 1 + (PWL - allowable) / spread, clamped at zero.",
                "Downstream length is informational; weld and fitting exposure not modelled.",
                "Move to a validated AIV assessment and qualified piping-vibration review.",
            ),
        )

    @staticmethod
    def _risk_warning(lof: float) -> str:
        if lof > 1.0:
            return "high-risk"
        if lof >= 0.5:
            return "medium-risk"
        return "low-risk"

    @staticmethod
    def _require_finite(name: str, value: float) -> None:
        if not isfinite(value):
            raise ValueError(f"{name} must be finite")

    @classmethod
    def _require_positive(cls, name: str, value: float) -> None:
        cls._require_finite(name, value)
        if value <= 0.0:
            raise ValueError(f"{name} must be positive")
