"""Eclipse VFPPROD lift-curve table import/export and post-processing.

Pure-Python (no numpy) reproduction of the VFPPROD reader/writer used for
reservoir-simulator coupling. The exporter and parser round-trip: parsing the
text produced by :func:`format_eclipse_vfp` reproduces the input axes and matrix.
"""
from __future__ import annotations

import math
import re
from dataclasses import dataclass, field
from pathlib import Path

Matrix = list[list[float]]

_MAX_LINE = 120
_COMMENT_KEYS = ("table no", "stage", "compressor", "bundle", "gear",
                 "configuration", "operations", "region")


@dataclass
class VFPTable:
    """A parsed Eclipse VFPPROD table."""

    table_id: int
    datum_depth: float
    flow_rates: list[float]
    outlet_pressures: list[float]
    inlet_pressures: Matrix  # shape (len(outlet_pressures), len(flow_rates))
    source_file: str = ""
    comments: list[str] = field(default_factory=list)

    @property
    def flow_rates_MSm3d(self) -> list[float]:
        return [q / 1e6 for q in self.flow_rates]

    @property
    def default_label(self) -> str:
        parts: list[str] = []
        for c in self.comments:
            cl = c.lstrip("- ").strip()
            if not any(k in cl.lower() for k in _COMMENT_KEYS):
                continue
            if ":" in cl:
                val = cl.split(":", 1)[1].strip()
            else:
                tokens = cl.split(None, 1)
                val = tokens[1].strip() if len(tokens) > 1 else cl
            val = re.sub(r"\s*\([^)]*\.yaml[^)]*\)\s*$", "", val).strip()
            if val:
                parts.append(val)
        if parts:
            return f"T{self.table_id} " + " | ".join(parts)
        return f"T{self.table_id}"


# ---------------------------------------------------------------------------
# Post-processing
# ---------------------------------------------------------------------------
def enforce_monotonic(rows: Matrix) -> Matrix:
    """Return a copy of ``rows`` with each row made non-decreasing.

    A lift curve (inlet pressure vs flow at fixed outlet pressure) must rise
    with flow. NaN cells are left untouched and do not reset the running max.
    """
    out: Matrix = []
    for row in rows:
        new_row = list(row)
        running = -math.inf
        for i, v in enumerate(new_row):
            if v is None or (isinstance(v, float) and math.isnan(v)):
                continue
            if v < running:
                new_row[i] = running
            else:
                running = v
        out.append(new_row)
    return out


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------
def format_eclipse_vfp(
    table_id: int,
    datum_depth: float,
    flow_rates_sm3day: list[float],
    outlet_pressures_bara: list[float],
    inlet_pressure_matrix: Matrix,
    traceability: dict | None = None,
    failure_value: float = 999.0,
) -> str:
    """Format a METRIC VFPPROD table with a traceability comment header.

    ``inlet_pressure_matrix`` has shape ``(len(outlet_pressures), len(flow_rates))``.
    NaN cells are written as ``failure_value``.
    """
    n_pout = len(outlet_pressures_bara)
    n_flow = len(flow_rates_sm3day)
    if len(inlet_pressure_matrix) != n_pout:
        raise ValueError("matrix rows must equal number of outlet pressures")
    for r in inlet_pressure_matrix:
        if len(r) != n_flow:
            raise ValueError("each matrix row must equal number of flow rates")

    lines: list[str] = []
    t = traceability or {}
    lines.append(f"-- VFP Table {table_id} - Generated by VFP Generator")
    if "conf_id" in t:
        lines.append(f"-- Configuration: {t['conf_id']}")
    if "ops_id" in t:
        lines.append(f"-- Operations: {t['ops_id']}")
    if "region" in t:
        lines.append(f"-- Region: {t['region']}")
    if "generated" in t:
        lines.append(f"-- Generated: {t['generated']}")
    if t.get("hard_constraints"):
        lines.append(f"-- Hard constraints: {', '.join(t['hard_constraints'])}")
    if t.get("soft_constraints"):
        lines.append(f"-- Soft constraints: {', '.join(t['soft_constraints'])}")
    lines.append("")

    lines.append("VFPPROD")
    lines.append("")
    lines.append(f"  {table_id}  {datum_depth:.0f}  'GAS'  'WGR'  'OGR' THP ' ' METRIC /")
    lines.append("")

    lines.extend(_wrap_values([f"{q:.6E}" for q in flow_rates_sm3day]))
    lines.extend(_wrap_values([f"{p:.4f}" for p in outlet_pressures_bara]))
    # WFR, GFR, ALQ axes (single dummy value each)
    lines.append(" 1 /")
    lines.append(" 1 /")
    lines.append(" 1 /")
    lines.append("")

    for row_idx in range(n_pout):
        cells: list[str] = []
        for v in inlet_pressure_matrix[row_idx]:
            if v is None or (isinstance(v, float) and math.isnan(v)):
                cells.append(f"{failure_value:.4f}")
            else:
                cells.append(f"{float(v):.4f}")
        # Eclipse row index quadruple: THP WFR GFR ALQ then BHP values
        prefix = f"  {row_idx + 1}  1  1  1 "
        body = " ".join(cells)
        lines.append(prefix + " " + body + " /")
    lines.append("")
    return "\n".join(lines) + "\n"


def _wrap_values(tokens: list[str]) -> list[str]:
    out: list[str] = []
    line = " "
    for tok in tokens:
        piece = " " + tok
        if len(line) + len(piece) > _MAX_LINE:
            out.append(line)
            line = " " + piece
        else:
            line += piece
    out.append(line)
    out.append("/")
    out.append("")
    return out


# ---------------------------------------------------------------------------
# Import
# ---------------------------------------------------------------------------
def _read_slash_terminated(lines: list[str], start: int) -> tuple[list[float], int]:
    values: list[float] = []
    i = start
    while i < len(lines):
        line = lines[i].strip()
        i += 1
        if not line or line.startswith("--"):
            continue
        terminated = "/" in line
        line = line.replace("/", "").strip()
        if line:
            values.extend(float(x) for x in line.split())
        if terminated:
            break
    return values, i


def parse_vfp_text(text: str, source_file: str = "") -> list[VFPTable]:
    """Parse VFPPROD tables from raw text."""
    lines = text.splitlines()
    tables: list[VFPTable] = []
    pending_comments: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith("--"):
            pending_comments.append(line[2:].strip())
            i += 1
            continue
        if line == "VFPPROD":
            i += 1
            while i < len(lines) and (not lines[i].strip() or lines[i].strip().startswith("--")):
                i += 1
            hdr = lines[i].replace("/", "").replace("'", "").split()
            table_id = int(hdr[0])
            datum_depth = float(hdr[1])
            i += 1
            flow_vals, i = _read_slash_terminated(lines, i)
            pout_vals, i = _read_slash_terminated(lines, i)
            _, i = _read_slash_terminated(lines, i)
            _, i = _read_slash_terminated(lines, i)
            _, i = _read_slash_terminated(lines, i)
            n_pout = len(pout_vals)
            n_flow = len(flow_vals)
            matrix: Matrix = [[math.nan] * n_flow for _ in range(n_pout)]
            for row_idx in range(n_pout):
                row_vals, i = _read_slash_terminated(lines, i)
                bhp_values = row_vals[4:]
                for col, v in enumerate(bhp_values):
                    if col < n_flow:
                        matrix[row_idx][col] = v
            tables.append(VFPTable(
                table_id=table_id,
                datum_depth=datum_depth,
                flow_rates=list(flow_vals),
                outlet_pressures=list(pout_vals),
                inlet_pressures=matrix,
                source_file=source_file,
                comments=pending_comments.copy(),
            ))
            pending_comments.clear()
        else:
            i += 1
    return tables


def parse_vfp_file(filepath: str | Path) -> list[VFPTable]:
    """Parse VFPPROD tables from a ``.VFP`` file."""
    filepath = Path(filepath)
    text = filepath.read_text(encoding="utf-8", errors="replace")
    return parse_vfp_text(text, source_file=filepath.name)


def load_vfp_dir(dirpath: str | Path) -> dict[int, VFPTable]:
    """Load all ``*.VFP`` files in a directory, keyed by table id."""
    dirpath = Path(dirpath)
    result: dict[int, VFPTable] = {}
    for fp in sorted(dirpath.glob("*.VFP")):
        for table in parse_vfp_file(fp):
            result[table.table_id] = table
    return result
