"""Generate, run and read back a complete OpenFOAM case.

The case is built from CFD boundary conditions that came out of a NeqSim flash and
a geometry that came out of a design basis, so every number in the case is
traceable. Nothing is copied from a tutorial and silently edited: every dictionary
is written explicitly, which is what makes the case reviewable.

Two case types are produced:

``OpenFoamCase``
    Steady, single-phase RANS - the carrier-fluid solve behind pressure drop,
    wall shear and local velocity peaks.
``VofOpenFoamCase``
    Transient volume of fluid - two phases from one NeqSim flash with a resolved
    interface, for stratified, slug and annular flow and for free surfaces.

Two mesh generators are built in - an O-grid round duct and a rectangular duct -
and any externally generated mesh (Gmsh, Fluent, I-deas, or an existing polyMesh)
can be imported instead, so arbitrary geometry is covered.

Writing a case never requires OpenFOAM to be installed. Running it does; when the
environment is absent the run is reported as not executed rather than raising, so
the generated case can still be inspected, committed or transferred.
"""

from __future__ import annotations

import os
import re
import shlex
import shutil
import subprocess
from dataclasses import dataclass, field
from math import cos, isfinite, radians, sin
from pathlib import Path
from typing import Any, Sequence

from .boundary import CfdBoundaryConditions
from .multiphase import GRAVITY_M_PER_S2, MultiphaseBoundaryConditions

_HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
| Generated by the NeqSim cfd-coupling skill. Every entry is derived from the
| design basis and the NeqSim fluid state; nothing is inherited from a tutorial.
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    format      ascii;
    class       {class_name};
    location    "{location}";
    object      {object_name};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""

# OpenFOAM.org v11+ uses module solvers via foamRun; earlier releases and the ESI
# fork use standalone applications and different dictionary names and entries.
_FLAVOURS: dict[str, dict[str, Any]] = {
    "org": {
        "properties_file": "physicalProperties",
        "turbulence_file": "momentumTransport",
        "model_key": "model",
        "viscosity_entry": "viscosityModel  constant;",
        "dimensioned_nu": False,
        "single_phase_application": "foamRun",
        "vof_application": "foamRun",
        "vof_solver": "incompressibleVoF",
        "phase_properties_file": "phaseProperties",
    },
    "legacy": {
        "properties_file": "transportProperties",
        "turbulence_file": "turbulenceProperties",
        "model_key": "RASModel",
        "viscosity_entry": "transportModel  Newtonian;",
        "dimensioned_nu": True,
        "single_phase_application": "simpleFoam",
        "vof_application": "interFoam",
        "vof_solver": None,
        "phase_properties_file": "transportProperties",
    },
}

_MESH_CONVERTERS = {
    ".msh": "gmshToFoam",
    ".unv": "ideasUnvToFoam",
    ".cas": "fluentMeshToFoam",
    ".cgns": "cfx4ToFoam",
}

# Cell-to-cell growth beyond this degrades gradient accuracy near the wall.
_MAX_CELL_EXPANSION = 1.3


@dataclass(frozen=True)
class MeshSpec:
    """Geometry and cell counts for the CFD mesh.

    ``kind`` is one of ``pipe`` (O-grid round duct), ``bend`` (O-grid elbow with
    straight lead-in and lead-out), ``channel`` (rectangular duct) or ``external``
    (import a mesh produced elsewhere). Lengths are metres. When
    ``first_cell_height_m`` is given, the near-wall grading is solved so the first
    cell matches it, which is how a y+ target from the fluid state reaches the mesh.
    """

    kind: str = "pipe"
    diameter_m: float | None = None
    length_m: float | None = None
    height_m: float | None = None
    width_m: float | None = None
    bend_radius_m: float | None = None
    bend_angle_deg: float = 90.0
    inlet_length_m: float | None = None
    outlet_length_m: float | None = None
    axial_cells: int = 60
    radial_cells: int = 12
    tangential_cells: int = 12
    core_fraction: float = 0.5
    first_cell_height_m: float | None = None
    mesh_file: str | None = None
    convert_command: str | None = None
    scale: float = 1.0

    def __post_init__(self) -> None:
        kind = self.kind.strip().lower()
        if kind not in {"pipe", "bend", "channel", "external"}:
            raise ValueError("kind must be 'pipe', 'bend', 'channel' or 'external'")
        if kind == "pipe":
            _require_positive("diameter_m", self.diameter_m)
            _require_positive("length_m", self.length_m)
        elif kind == "bend":
            _require_positive("diameter_m", self.diameter_m)
            _require_positive("bend_radius_m", self.bend_radius_m)
            _require_positive("inlet_length_m", self.inlet_length_m)
            _require_positive("outlet_length_m", self.outlet_length_m)
            if not 0.0 < self.bend_angle_deg <= 180.0:
                raise ValueError("bend_angle_deg must lie between 0 and 180")
            if self.bend_radius_m < 0.5 * self.diameter_m:
                raise ValueError("bend_radius_m below half the diameter folds the mesh")
        elif kind == "channel":
            _require_positive("height_m", self.height_m)
            _require_positive("width_m", self.width_m)
            _require_positive("length_m", self.length_m)
        elif not self.mesh_file:
            raise ValueError("an external mesh requires mesh_file")
        if kind in {"pipe", "bend"} and not 0.1 <= self.core_fraction <= 0.8:
            raise ValueError("core_fraction must lie between 0.1 and 0.8")
        for name in ("axial_cells", "radial_cells", "tangential_cells"):
            if int(getattr(self, name)) < 1:
                raise ValueError(f"{name} must be at least 1")

    @property
    def hydraulic_diameter_m(self) -> float | None:
        """Hydraulic diameter implied by the geometry, when it is known."""
        if self.kind in {"pipe", "bend"}:
            return self.diameter_m
        if self.kind == "channel":
            return 2.0 * self.height_m * self.width_m / (self.height_m + self.width_m)
        return None


@dataclass(frozen=True)
class RunStep:
    """One command in the case workflow and how it ended."""

    command: str
    returncode: int | None
    stdout_tail: str
    stderr_tail: str

    @property
    def succeeded(self) -> bool:
        return self.returncode == 0


@dataclass(frozen=True)
class RunOutcome:
    """Result of executing the case workflow."""

    status: str
    steps: tuple[RunStep, ...]
    environment: str
    message: str

    @property
    def executed(self) -> bool:
        return self.status in {"completed", "failed"}


@dataclass(frozen=True)
class OpenFoamResults:
    """Engineering quantities recovered from a solved case."""

    inlet_volumetric_flow_m3_per_s: float | None
    outlet_volumetric_flow_m3_per_s: float | None
    continuity_error_relative: float | None
    pressure_drop_pa: float | None
    peak_wall_shear_pa: float | None
    mean_wall_shear_pa: float | None
    y_plus_min: float | None
    y_plus_mean: float | None
    y_plus_max: float | None
    outlet_dispersed_fraction: float | None
    findings: tuple[str, ...]

    @property
    def wall_shear_enhancement(self) -> float | None:
        """Peak-to-mean wall shear, the factor a one-dimensional model is missing."""
        if not self.peak_wall_shear_pa or not self.mean_wall_shear_pa:
            return None
        return self.peak_wall_shear_pa / self.mean_wall_shear_pa


class _FoamCaseBase:
    """Case-tree writing, meshing and execution shared by every case type.

    Subclasses are dataclasses supplying ``mesh``, ``flavour``, ``wall_treatment``,
    ``inlet_patch``, ``outlet_patch``, ``wall_patches``, ``axis`` and
    ``extra_notes``, and implementing ``_system_files``, ``_constant_files``,
    ``_initial_files`` and ``commands``.
    """

    def _validate_common(self) -> None:
        if self.flavour not in _FLAVOURS:
            raise ValueError("flavour must be 'org' (OpenFOAM v11+) or 'legacy'")
        if self.wall_treatment not in {"wall_function", "resolved"}:
            raise ValueError("wall_treatment must be 'wall_function' or 'resolved'")
        if self.axis not in {"x", "y", "z"}:
            raise ValueError("axis must be 'x', 'y' or 'z'")
        if not self.wall_patches:
            raise ValueError("at least one wall patch is required")

    def write(self, case_dir: str | Path, *, overwrite: bool = False) -> tuple[str, ...]:
        """Write the whole case tree and return the relative paths written."""
        root = Path(case_dir)
        if root.exists():
            if not overwrite:
                raise FileExistsError(f"{root} already exists; pass overwrite=True to replace it")
            shutil.rmtree(root)

        files = dict(self._system_files())
        files.update(self._constant_files())
        files.update(self._initial_files())

        for relative, text in files.items():
            target = root / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")

        if self.mesh.kind == "external" and self.mesh.mesh_file:
            source = Path(self.mesh.mesh_file)
            if source.is_file():
                shutil.copyfile(source, root / source.name)
                files[source.name] = ""

        return tuple(sorted(files))

    def run(
        self,
        case_dir: str | Path,
        *,
        timeout_seconds: int = 1800,
        bashrc: str | None = None,
    ) -> RunOutcome:
        """Execute the case workflow, or report that OpenFOAM is unavailable."""
        environment = detect_openfoam(bashrc=bashrc)
        if environment is None:
            return RunOutcome(
                status="not_executed",
                steps=(),
                environment="none",
                message=(
                    "OpenFOAM was not found. The case has been written and can be run "
                    "elsewhere with: " + " && ".join(self.commands())
                ),
            )

        root = Path(case_dir)
        steps: list[RunStep] = []
        for command in self.commands():
            completed = _run_foam_command(command, root, environment, timeout_seconds)
            steps.append(completed)
            if not completed.succeeded:
                return RunOutcome(
                    status="failed",
                    steps=tuple(steps),
                    environment=environment,
                    message=f"'{command}' failed; inspect the captured output.",
                )

        return RunOutcome(
            status="completed",
            steps=tuple(steps),
            environment=environment,
            message="All case commands completed.",
        )

    def mesh_warnings(self) -> tuple[str, ...]:
        """Report near-wall grading that would produce a poor-quality mesh.

        A first-cell height that is very small relative to the number of cells
        available forces a steep expansion. Cell-to-cell ratios above about 1.3
        degrade gradient accuracy, and the fix is more cells, not a coarser wall.
        """
        if self.mesh.kind == "external" or self.mesh.first_cell_height_m is None:
            return ()

        if self.mesh.kind == "pipe":
            thickness = (self.mesh.diameter_m / 2.0) * (1.0 - self.mesh.core_fraction)
            cells = self.mesh.radial_cells
            direction = "radial"
        elif self.mesh.kind == "bend":
            thickness = (self.mesh.diameter_m / 2.0) * (1.0 - self.mesh.core_fraction)
            cells = self.mesh.radial_cells
            direction = "radial"
        else:
            thickness = self.mesh.height_m / 2.0
            cells = max(1, self.mesh.radial_cells // 2)
            direction = "wall-normal"

        _, cell_ratio = _wall_grading(thickness, cells, self.mesh.first_cell_height_m)
        warnings: list[str] = []
        if cell_ratio > _MAX_CELL_EXPANSION:
            needed = _cells_for_ratio(thickness, self.mesh.first_cell_height_m)
            warnings.append(
                f"{direction.capitalize()} cell-to-cell expansion is {cell_ratio:.2f}, above the "
                f"{_MAX_CELL_EXPANSION} normally accepted. Increase the {direction} cell count to "
                f"about {needed} to reach the requested "
                f"{self.mesh.first_cell_height_m * 1e3:.3f} mm first cell without over-stretching."
            )
        if self.mesh.first_cell_height_m * cells >= thickness:
            warnings.append(
                "The requested first cell is too large for the number of cells available, "
                "so no grading was applied and the y+ target will not be met."
            )
        return tuple(warnings)

    # ------------------------------------------------------------ shared pieces

    def _mesh_commands(self) -> list[str]:
        first = self._conversion_command() if self.mesh.kind == "external" else "blockMesh"
        return [first, "checkMesh -constant"]

    def _block_mesh_dict(self) -> str:
        if self.mesh.kind == "pipe":
            body = _pipe_block_mesh(
                self.mesh, self.inlet_patch, self.outlet_patch, self.wall_patches[0]
            )
        elif self.mesh.kind == "bend":
            body = _bend_block_mesh(
                self.mesh, self.inlet_patch, self.outlet_patch, self.wall_patches[0]
            )
        else:
            body = _channel_block_mesh(
                self.mesh, self.inlet_patch, self.outlet_patch, self.wall_patches[0]
            )
        return _foam_file("dictionary", "system", "blockMeshDict") + body

    def _conversion_command(self) -> str:
        if self.mesh.convert_command:
            return self.mesh.convert_command
        suffix = Path(self.mesh.mesh_file or "").suffix.lower()
        converter = _MESH_CONVERTERS.get(suffix)
        if converter is None:
            raise ValueError(
                f"no converter known for '{suffix}'; set MeshSpec.convert_command explicitly"
            )
        name = Path(self.mesh.mesh_file or "").name
        scale = f" -scale {self.mesh.scale:g}" if self.mesh.scale != 1.0 else ""
        return f"{converter}{scale} {shlex.quote(name)}"

    def _turbulence_file(self, model: str, *, laminar: bool = False) -> tuple[str, str]:
        spec = _FLAVOURS[self.flavour]
        path = f"constant/{spec['turbulence_file']}"
        header = _foam_file("dictionary", "constant", spec["turbulence_file"])
        if laminar:
            return path, header + "\nsimulationType  laminar;\n"
        return path, header + f"""
simulationType  RAS;

RAS
{{
    {spec['model_key']}         {model};
    turbulence      on;
    printCoeffs     on;
}}
"""

    def _wall_entry(self, patch_type: str, value: str | None) -> str:
        blocks = []
        for patch in self.wall_patches:
            value_line = f"\n        value           uniform {value};" if value is not None else ""
            blocks.append(
                f"""    {patch}
    {{
        type            {patch_type};{value_line}
    }}"""
            )
        return "\n\n".join(blocks)

    @staticmethod
    def _default_entry() -> str:
        return """
    "(front|back|symmetry.*|.*Empty)"
    {
        type            empty;
    }"""

    def _axis_vector(self, magnitude: float) -> str:
        components = {"x": (magnitude, 0.0, 0.0), "y": (0.0, magnitude, 0.0)}.get(
            self.axis, (0.0, 0.0, magnitude)
        )
        return "({:.8g} {:.8g} {:.8g})".format(*components)

    def _notes(self) -> str:
        return "".join(f"// {note}\n" for note in self.extra_notes)

    @staticmethod
    def _surface_field_value(name: str, patch: str, operation: str, field_name: str) -> str:
        return f"""    {name}
    {{
        type            surfaceFieldValue;
        libs            ("libfieldFunctionObjects.so");
        regionType      patch;
        name            {patch};
        operation       {operation};
        fields          ({field_name});
        writeFields     no;
        writeControl    writeTime;
        executeControl  writeTime;
        log             true;
    }}"""

    def _turbulence_field_entries(
        self, inlet_value: str, wall_type: str, wall_value: str | None
    ) -> str:
        return f"""
boundaryField
{{
    {self.inlet_patch}
    {{
        type            fixedValue;
        value           uniform {inlet_value};
    }}

    {self.outlet_patch}
    {{
        type            inletOutlet;
        inletValue      uniform {inlet_value};
        value           uniform {inlet_value};
    }}

{self._wall_entry(wall_type, wall_value)}
{self._default_entry()}
}}
"""


@dataclass
class OpenFoamCase(_FoamCaseBase):
    """A steady single-phase OpenFOAM case built from NeqSim boundary data."""

    boundary: CfdBoundaryConditions
    mesh: MeshSpec
    name: str = "neqsim_case"
    flavour: str = "org"
    end_time: int = 1000
    write_interval: int = 250
    residual_target: float = 1.0e-5
    wall_treatment: str = "wall_function"
    inlet_patch: str = "inlet"
    outlet_patch: str = "outlet"
    wall_patches: Sequence[str] = ("walls",)
    axis: str = "z"
    extra_notes: Sequence[str] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        self._validate_common()

    def commands(self) -> tuple[str, ...]:
        """Return the ordered shell commands that mesh, check and solve the case."""
        spec = _FLAVOURS[self.flavour]
        steps = self._mesh_commands()
        steps.append(spec["single_phase_application"])
        steps.append("foamToVTK -latestTime")
        return tuple(steps)

    # ------------------------------------------------------------------ content

    def _system_files(self) -> dict[str, str]:
        files = {
            "system/controlDict": self._control_dict(),
            "system/fvSchemes": self._fv_schemes(),
            "system/fvSolution": self._fv_solution(),
        }
        if self.mesh.kind != "external":
            files["system/blockMeshDict"] = self._block_mesh_dict()
        return files

    def _constant_files(self) -> dict[str, str]:
        spec = _FLAVOURS[self.flavour]
        fluid = self.boundary.fluid
        properties = _foam_file("dictionary", "constant", spec["properties_file"]) + f"""
// Kinematic viscosity from the NeqSim {fluid.phase} phase:
//   density   {fluid.density_kg_per_m3:.6g} kg/m3
//   viscosity {fluid.viscosity_pa_s:.6g} Pa s
{spec['viscosity_entry']}

{_nu_entry(spec, fluid.kinematic_viscosity_m2_per_s)}
"""
        turbulence_path, turbulence_text = self._turbulence_file(
            self.boundary.recommended_turbulence_model,
            laminar=self.boundary.flow_regime == "laminar",
        )
        return {
            f"constant/{spec['properties_file']}": properties,
            turbulence_path: turbulence_text,
        }

    def _initial_files(self) -> dict[str, str]:
        fields = {"0/U": self._field_u(), "0/p": self._field_p()}
        if self.boundary.flow_regime == "laminar":
            return fields
        fields["0/k"] = self._field_k()
        fields["0/nut"] = self._field_nut()
        if self.boundary.recommended_turbulence_model.lower().startswith("komega"):
            fields["0/omega"] = self._field_omega()
        else:
            fields["0/epsilon"] = self._field_epsilon()
        return fields

    def _control_dict(self) -> str:
        spec = _FLAVOURS[self.flavour]
        solver_entry = (
            f"solver          {self.boundary.recommended_solver};\n"
            if spec["vof_solver"] is not None
            else ""
        )
        return _foam_file("dictionary", "system", "controlDict") + f"""
{self._notes()}application     {spec['single_phase_application']};
{solver_entry}
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {self.end_time};
deltaT          1;

writeControl    timeStep;
writeInterval   {self.write_interval};
purgeWrite      0;
writeFormat     ascii;
writePrecision  8;
writeCompression off;
runTimeModifiable true;

functions
{{
{self._function_objects()}
}}
"""

    def _function_objects(self) -> str:
        walls = " ".join(self.wall_patches)
        blocks = [
            f"""    wallShearStress
    {{
        type            wallShearStress;
        libs            ("libfieldFunctionObjects.so");
        patches         ({walls});
        writeControl    writeTime;
        executeControl  writeTime;
    }}""",
            """    yPlus
    {
        type            yPlus;
        libs            ("libfieldFunctionObjects.so");
        writeControl    writeTime;
        executeControl  writeTime;
    }""",
            """    residuals
    {
        type            residuals;
        libs            ("libutilityFunctionObjects.so");
        writeControl    timeStep;
        writeInterval   1;
    }""",
            self._surface_field_value("inletFlux", self.inlet_patch, "sum", "phi"),
            self._surface_field_value("outletFlux", self.outlet_patch, "sum", "phi"),
            self._surface_field_value("inletPressure", self.inlet_patch, "areaAverage", "p"),
            self._surface_field_value("outletPressure", self.outlet_patch, "areaAverage", "p"),
        ]
        for patch in self.wall_patches:
            blocks.append(
                self._surface_field_value(
                    f"peakWallShear_{patch}", patch, "max", "wallShearStress"
                )
            )
            blocks.append(
                self._surface_field_value(
                    f"meanWallShear_{patch}", patch, "areaAverage", "wallShearStress"
                )
            )
        return "\n\n".join(blocks)

    def _fv_schemes(self) -> str:
        return _foam_file("dictionary", "system", "fvSchemes") + """
ddtSchemes      { default steadyState; }

gradSchemes     { default cellLimited Gauss linear 1; }

// Second-order upwind on momentum: first-order upwind would smear exactly the
// local peaks the coupling is trying to measure.
divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss linearUpwind grad(U);
    div(phi,k)      bounded Gauss limitedLinear 1;
    div(phi,omega)  bounded Gauss limitedLinear 1;
    div(phi,epsilon) bounded Gauss limitedLinear 1;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}

laplacianSchemes { default Gauss linear corrected; }

interpolationSchemes { default linear; }

snGradSchemes   { default corrected; }

wallDist        { method meshWave; }
"""

    def _fv_solution(self) -> str:
        return _foam_file("dictionary", "system", "fvSolution") + f"""
solvers
{{
    p
    {{
        solver          GAMG;
        tolerance       1e-07;
        relTol          0.01;
        smoother        GaussSeidel;
    }}

    "(U|k|omega|epsilon)"
    {{
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-08;
        relTol          0.01;
    }}
}}

SIMPLE
{{
    nNonOrthogonalCorrectors 1;
    consistent      yes;

    residualControl
    {{
        p               {self.residual_target:.1e};
        U               {self.residual_target:.1e};
        "(k|omega|epsilon)" {self.residual_target:.1e};
    }}
}}

relaxationFactors
{{
    equations
    {{
        U               0.9;
        ".*"            0.9;
    }}
}}
"""

    # ------------------------------------------------------------------- fields

    def _field_u(self) -> str:
        vector = self._axis_vector(self.boundary.velocity_m_per_s)
        return _foam_file("volVectorField", "0", "U") + f"""
dimensions      [0 1 -1 0 0 0 0];

internalField   uniform {vector};

boundaryField
{{
    {self.inlet_patch}
    {{
        type            fixedValue;
        value           uniform {vector};
    }}

    {self.outlet_patch}
    {{
        type            inletOutlet;
        inletValue      uniform (0 0 0);
        value           uniform {vector};
    }}

{self._wall_entry('noSlip', None)}
{self._default_entry()}
}}
"""

    def _field_p(self) -> str:
        return _foam_file("volScalarField", "0", "p") + f"""
// Kinematic pressure (m2/s2) for an incompressible solver.
// Multiply by density {self.boundary.fluid.density_kg_per_m3:.6g} kg/m3 to obtain Pa.
dimensions      [0 2 -2 0 0 0 0];

internalField   uniform 0;

boundaryField
{{
    {self.inlet_patch}
    {{
        type            zeroGradient;
    }}

    {self.outlet_patch}
    {{
        type            fixedValue;
        value           uniform 0;
    }}

{self._wall_entry('zeroGradient', None)}
{self._default_entry()}
}}
"""

    def _field_k(self) -> str:
        value = f"{self.boundary.turbulent_kinetic_energy_m2_per_s2:.8g}"
        wall_type = "kqRWallFunction" if self.wall_treatment == "wall_function" else "fixedValue"
        wall_value = value if self.wall_treatment == "wall_function" else "1e-12"
        return (
            _foam_file("volScalarField", "0", "k")
            + "\ndimensions      [0 2 -2 0 0 0 0];\n\n"
            + f"internalField   uniform {value};\n"
            + self._turbulence_field_entries(value, wall_type, wall_value)
        )

    def _field_omega(self) -> str:
        value = f"{self.boundary.specific_dissipation_1_per_s:.8g}"
        return (
            _foam_file("volScalarField", "0", "omega")
            + "\ndimensions      [0 0 -1 0 0 0 0];\n\n"
            + f"internalField   uniform {value};\n"
            + self._turbulence_field_entries(value, "omegaWallFunction", value)
        )

    def _field_epsilon(self) -> str:
        value = f"{self.boundary.turbulent_dissipation_m2_per_s3:.8g}"
        return (
            _foam_file("volScalarField", "0", "epsilon")
            + "\ndimensions      [0 2 -3 0 0 0 0];\n\n"
            + f"internalField   uniform {value};\n"
            + self._turbulence_field_entries(value, "epsilonWallFunction", value)
        )

    def _field_nut(self) -> str:
        wall_type = (
            "nutkWallFunction" if self.wall_treatment == "wall_function" else "nutLowReWallFunction"
        )
        return _foam_file("volScalarField", "0", "nut") + f"""
dimensions      [0 2 -1 0 0 0 0];

internalField   uniform 0;

boundaryField
{{
    {self.inlet_patch}
    {{
        type            calculated;
        value           uniform 0;
    }}

    {self.outlet_patch}
    {{
        type            calculated;
        value           uniform 0;
    }}

{self._wall_entry(wall_type, '0')}
{self._default_entry()}
}}
"""


@dataclass
class VofOpenFoamCase(_FoamCaseBase):
    """A transient volume-of-fluid case for two phases from one NeqSim flash.

    Volume of fluid resolves the interface, so it answers stratified, slug, annular
    and free-surface questions. It is the wrong tool for a dilute droplet mist: the
    multiphase screening says so, and this class refuses to build a case the
    screening did not recommend unless that is explicitly overridden.
    """

    boundary: MultiphaseBoundaryConditions
    mesh: MeshSpec
    name: str = "neqsim_vof_case"
    flavour: str = "org"
    end_time: float = 5.0
    write_interval: float = 0.25
    max_courant: float = 0.5
    max_alpha_courant: float = 0.5
    initial_time_step: float = 1.0e-4
    wall_treatment: str = "wall_function"
    inlet_patch: str = "inlet"
    outlet_patch: str = "outlet"
    wall_patches: Sequence[str] = ("walls",)
    axis: str = "z"
    gravity: tuple[float, float, float] = (0.0, -GRAVITY_M_PER_S2, 0.0)
    initial_dispersed_fraction: float = 0.0
    allow_unrecommended_model: bool = False
    extra_notes: Sequence[str] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        self._validate_common()
        if not 0.0 <= self.initial_dispersed_fraction <= 1.0:
            raise ValueError("initial_dispersed_fraction must lie between 0 and 1")
        if self.boundary.recommended_model != "vof" and not self.allow_unrecommended_model:
            raise ValueError(
                "the multiphase screening recommended "
                f"'{self.boundary.recommended_model}', not volume of fluid: "
                f"{self.boundary.model_rationale} Pass allow_unrecommended_model=True to "
                "build the case anyway and record the reason."
            )

    @property
    def dispersed_name(self) -> str:
        """OpenFOAM phase name for the tracked (alpha) phase."""
        return _foam_name(self.boundary.state.dispersed.phase)

    @property
    def continuous_name(self) -> str:
        """OpenFOAM phase name for the carrier phase."""
        return _foam_name(self.boundary.state.continuous.phase)

    def commands(self) -> tuple[str, ...]:
        """Return the ordered shell commands that mesh, initialise and solve."""
        spec = _FLAVOURS[self.flavour]
        steps = self._mesh_commands()
        steps.append("setFields")
        steps.append(spec["vof_application"])
        steps.append("foamToVTK -latestTime")
        return tuple(steps)

    # ------------------------------------------------------------------ content

    def _system_files(self) -> dict[str, str]:
        files = {
            "system/controlDict": self._control_dict(),
            "system/fvSchemes": self._fv_schemes(),
            "system/fvSolution": self._fv_solution(),
            "system/setFieldsDict": self._set_fields_dict(),
        }
        if self.mesh.kind != "external":
            files["system/blockMeshDict"] = self._block_mesh_dict()
        return files

    def _constant_files(self) -> dict[str, str]:
        spec = _FLAVOURS[self.flavour]
        state = self.boundary.state
        files = {
            "constant/g": _foam_file("uniformDimensionedVectorField", "constant", "g")
            + "\ndimensions      [0 1 -2 0 0 0 0];\n\n"
            + "value           ({:.6g} {:.6g} {:.6g});\n".format(*self.gravity),
        }

        header = (
            f"// Phase properties from one NeqSim flash at "
            f"{state.continuous.pressure_bara or float('nan'):.4g} bara.\n"
            f"// Interfacial tension {state.interfacial_tension_n_per_m:.6g} N/m.\n"
        )

        if self.flavour == "org":
            files["constant/phaseProperties"] = (
                _foam_file("dictionary", "constant", "phaseProperties")
                + f"""
{header}
phases          ({self.dispersed_name} {self.continuous_name});

sigma           {state.interfacial_tension_n_per_m:.8g};
"""
            )
            for name, phase in (
                (self.dispersed_name, state.dispersed),
                (self.continuous_name, state.continuous),
            ):
                files[f"constant/physicalProperties.{name}"] = (
                    _foam_file("dictionary", "constant", f"physicalProperties.{name}")
                    + f"""
viscosityModel  constant;

nu              {phase.kinematic_viscosity_m2_per_s:.8g};
rho             {phase.density_kg_per_m3:.8g};
"""
                )
        else:
            files["constant/transportProperties"] = (
                _foam_file("dictionary", "constant", "transportProperties")
                + f"""
{header}
phases          ({self.dispersed_name} {self.continuous_name});

{self.dispersed_name}
{{
    transportModel  Newtonian;
    nu              [0 2 -1 0 0 0 0] {state.dispersed.kinematic_viscosity_m2_per_s:.8g};
    rho             [1 -3 0 0 0 0 0] {state.dispersed.density_kg_per_m3:.8g};
}}

{self.continuous_name}
{{
    transportModel  Newtonian;
    nu              [0 2 -1 0 0 0 0] {state.continuous.kinematic_viscosity_m2_per_s:.8g};
    rho             [1 -3 0 0 0 0 0] {state.continuous.density_kg_per_m3:.8g};
}}

sigma           [1 0 -2 0 0 0 0] {state.interfacial_tension_n_per_m:.8g};
"""
            )

        turbulence_path, turbulence_text = self._turbulence_file(
            "kOmegaSST", laminar=self.boundary.mixture_reynolds < 4000.0
        )
        files[turbulence_path] = turbulence_text
        return files

    def _initial_files(self) -> dict[str, str]:
        fields = {
            f"0/alpha.{self.dispersed_name}": self._field_alpha(),
            "0/U": self._field_u(),
            "0/p_rgh": self._field_p_rgh(),
        }
        if self.boundary.mixture_reynolds >= 4000.0:
            value_k = f"{self.boundary.turbulent_kinetic_energy_m2_per_s2:.8g}"
            value_omega = f"{self.boundary.specific_dissipation_1_per_s:.8g}"
            wall_k = "kqRWallFunction" if self.wall_treatment == "wall_function" else "fixedValue"
            fields["0/k"] = (
                _foam_file("volScalarField", "0", "k")
                + "\ndimensions      [0 2 -2 0 0 0 0];\n\n"
                + f"internalField   uniform {value_k};\n"
                + self._turbulence_field_entries(value_k, wall_k, value_k)
            )
            fields["0/omega"] = (
                _foam_file("volScalarField", "0", "omega")
                + "\ndimensions      [0 0 -1 0 0 0 0];\n\n"
                + f"internalField   uniform {value_omega};\n"
                + self._turbulence_field_entries(value_omega, "omegaWallFunction", value_omega)
            )
            wall_nut = (
                "nutkWallFunction"
                if self.wall_treatment == "wall_function"
                else "nutLowReWallFunction"
            )
            fields["0/nut"] = _foam_file("volScalarField", "0", "nut") + f"""
dimensions      [0 2 -1 0 0 0 0];

internalField   uniform 0;

boundaryField
{{
    {self.inlet_patch}
    {{
        type            calculated;
        value           uniform 0;
    }}

    {self.outlet_patch}
    {{
        type            calculated;
        value           uniform 0;
    }}

{self._wall_entry(wall_nut, '0')}
{self._default_entry()}
}}
"""
        return fields

    def _control_dict(self) -> str:
        spec = _FLAVOURS[self.flavour]
        solver_entry = (
            f"solver          {spec['vof_solver']};\n" if spec["vof_solver"] else ""
        )
        return _foam_file("dictionary", "system", "controlDict") + f"""
{self._notes()}// Transient by necessity: an interface has no steady state.
application     {spec['vof_application']};
{solver_entry}
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {self.end_time:g};
deltaT          {self.initial_time_step:g};

writeControl    adjustableRunTime;
writeInterval   {self.write_interval:g};
purgeWrite      0;
writeFormat     ascii;
writePrecision  8;
writeCompression off;
runTimeModifiable true;

adjustTimeStep  yes;
maxCo           {self.max_courant:g};
maxAlphaCo      {self.max_alpha_courant:g};
maxDeltaT       {self.write_interval / 10.0:g};

functions
{{
{self._function_objects()}
}}
"""

    def _function_objects(self) -> str:
        alpha = f"alpha.{self.dispersed_name}"
        blocks = [
            self._surface_field_value("inletFlux", self.inlet_patch, "sum", "phi"),
            self._surface_field_value("outletFlux", self.outlet_patch, "sum", "phi"),
            self._surface_field_value(
                "outletDispersedFraction", self.outlet_patch, "areaAverage", alpha
            ),
            self._surface_field_value("inletPressure", self.inlet_patch, "areaAverage", "p_rgh"),
            self._surface_field_value("outletPressure", self.outlet_patch, "areaAverage", "p_rgh"),
            f"""    dispersedInventory
    {{
        type            volFieldValue;
        libs            ("libfieldFunctionObjects.so");
        regionType      all;
        operation       volIntegrate;
        fields          ({alpha});
        writeFields     no;
        writeControl    writeTime;
        executeControl  writeTime;
        log             true;
    }}""",
        ]
        return "\n\n".join(blocks)

    def _fv_schemes(self) -> str:
        alpha = f"alpha.{self.dispersed_name}"
        return _foam_file("dictionary", "system", "fvSchemes") + f"""
// Euler in time and a compressive interface scheme: vanLeer on the phase
// fraction keeps the interface sharp without smearing it across the mesh.
ddtSchemes      {{ default Euler; }}

gradSchemes     {{ default Gauss linear; }}

divSchemes
{{
    default         none;
    div(rhoPhi,U)   Gauss linearUpwind grad(U);
    div(phi,alpha)  Gauss vanLeer;
    div(phirb,alpha) Gauss linear;
    "div\\(phi,(k|omega|epsilon)\\)" Gauss limitedLinear 1;
    div(((rho*nuEff)*dev2(T(grad(U))))) Gauss linear;
}}

laplacianSchemes {{ default Gauss linear corrected; }}

interpolationSchemes {{ default linear; }}

snGradSchemes   {{ default corrected; }}

wallDist        {{ method meshWave; }}

// Tracked phase fraction: {alpha}
"""

    def _fv_solution(self) -> str:
        alpha = f"alpha.{self.dispersed_name}"
        return _foam_file("dictionary", "system", "fvSolution") + f"""
solvers
{{
    "{alpha}.*"
    {{
        nAlphaCorr      2;
        nAlphaSubCycles 1;
        cAlpha          1;
        MULESCorr       yes;
        nLimiterIter    5;
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-08;
        relTol          0;
    }}

    "pcorr.*"
    {{
        solver          PCG;
        preconditioner  DIC;
        tolerance       1e-05;
        relTol          0;
    }}

    p_rgh
    {{
        solver          GAMG;
        smoother        DIC;
        tolerance       1e-07;
        relTol          0.05;
    }}

    p_rghFinal
    {{
        $p_rgh;
        relTol          0;
    }}

    "(U|k|omega|epsilon).*"
    {{
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-07;
        relTol          0;
    }}
}}

PIMPLE
{{
    momentumPredictor   no;
    nOuterCorrectors    1;
    nCorrectors         3;
    nNonOrthogonalCorrectors 0;
}}
"""

    def _set_fields_dict(self) -> str:
        alpha = f"alpha.{self.dispersed_name}"
        return _foam_file("dictionary", "system", "setFieldsDict") + f"""
// Uniform initial state. Add a boxToCell region here to start from a liquid
// layer or a filled section instead of a uniform mixture.
defaultFieldValues
(
    volScalarFieldValue {alpha} {self.initial_dispersed_fraction:.6g}
);

regions
(
);
"""

    def _field_alpha(self) -> str:
        inlet = f"{self.boundary.state.dispersed_volume_fraction:.8g}"
        return _foam_file("volScalarField", "0", f"alpha.{self.dispersed_name}") + f"""
// Volume fraction of the {self.boundary.state.dispersed.phase} phase.
// Inlet value is the NeqSim flash phase split at the inlet condition.
dimensions      [0 0 0 0 0 0 0];

internalField   uniform {self.initial_dispersed_fraction:.8g};

boundaryField
{{
    {self.inlet_patch}
    {{
        type            fixedValue;
        value           uniform {inlet};
    }}

    {self.outlet_patch}
    {{
        type            inletOutlet;
        inletValue      uniform 0;
        value           uniform 0;
    }}

{self._wall_entry('zeroGradient', None)}
{self._default_entry()}
}}
"""

    def _field_u(self) -> str:
        vector = self._axis_vector(self.boundary.mixture_velocity_m_per_s)
        return _foam_file("volVectorField", "0", "U") + f"""
// Homogeneous mixture velocity: superficial continuous
// {self.boundary.superficial_continuous_velocity_m_per_s:.4g} m/s plus superficial
// dispersed {self.boundary.superficial_dispersed_velocity_m_per_s:.4g} m/s.
// Slip between the phases develops in the solution, not at the inlet.
dimensions      [0 1 -1 0 0 0 0];

internalField   uniform {vector};

boundaryField
{{
    {self.inlet_patch}
    {{
        type            fixedValue;
        value           uniform {vector};
    }}

    {self.outlet_patch}
    {{
        type            inletOutlet;
        inletValue      uniform (0 0 0);
        value           uniform {vector};
    }}

{self._wall_entry('noSlip', None)}
{self._default_entry()}
}}
"""

    def _field_p_rgh(self) -> str:
        return _foam_file("volScalarField", "0", "p_rgh") + f"""
// p_rgh = p - rho*g*h, so the hydrostatic head is carried separately.
dimensions      [1 -1 -2 0 0 0 0];

internalField   uniform 0;

boundaryField
{{
    {self.inlet_patch}
    {{
        type            fixedFluxPressure;
        value           uniform 0;
    }}

    {self.outlet_patch}
    {{
        type            totalPressure;
        p0              uniform 0;
        value           uniform 0;
    }}

{self._wall_entry('fixedFluxPressure', '0')}
{self._default_entry()}
}}
"""


# ------------------------------------------------------------------- mesh text


def _pipe_block_mesh(mesh: MeshSpec, inlet: str, outlet: str, wall: str) -> str:
    """O-grid blockMeshDict for a round duct, graded towards the wall."""
    radius = mesh.diameter_m / 2.0
    core_radius = mesh.core_fraction * radius
    length = mesh.length_m
    angles = [radians(45.0 + 90.0 * k) for k in range(4)]

    def point(r: float, angle: float, z: float) -> str:
        return f"    ({r * cos(angle):.8g} {r * sin(angle):.8g} {z:.8g})"

    vertices: list[str] = []
    for z in (0.0, length):
        vertices.extend(point(core_radius, angle, z) for angle in angles)
        vertices.extend(point(radius, angle, z) for angle in angles)

    grading, cell_ratio = _wall_grading(
        radius - core_radius, mesh.radial_cells, mesh.first_cell_height_m
    )

    inner = [0, 1, 2, 3]
    outer = [4, 5, 6, 7]
    blocks = [
        f"    hex (0 1 2 3 8 9 10 11) "
        f"({mesh.tangential_cells} {mesh.tangential_cells} {mesh.axial_cells}) "
        f"simpleGrading (1 1 1)"
    ]
    edges: list[str] = []
    wall_faces: list[str] = []
    inlet_faces = ["        (3 2 1 0)"]
    outlet_faces = ["        (8 9 10 11)"]

    for k in range(4):
        nxt = (k + 1) % 4
        o0, o1 = outer[k], outer[nxt]
        i0, i1 = inner[k], inner[nxt]
        blocks.append(
            f"    hex ({o0} {o1} {i1} {i0} {o0 + 8} {o1 + 8} {i1 + 8} {i0 + 8}) "
            f"({mesh.tangential_cells} {mesh.radial_cells} {mesh.axial_cells}) "
            f"simpleGrading (1 {grading:.6g} 1)"
        )
        mid_angle = radians(90.0 + 90.0 * k)
        for z, offset in ((0.0, 0), (length, 8)):
            edges.append(
                f"    arc {o0 + offset} {o1 + offset} "
                f"({radius * cos(mid_angle):.8g} {radius * sin(mid_angle):.8g} {z:.8g})"
            )
        wall_faces.append(f"        ({o0} {o1} {o1 + 8} {o0 + 8})")
        inlet_faces.append(f"        ({i0} {i1} {o1} {o0})")
        outlet_faces.append(f"        ({o0 + 8} {o1 + 8} {i1 + 8} {i0 + 8})")

    return f"""
// O-grid round duct: diameter {mesh.diameter_m:g} m, length {mesh.length_m:g} m.
// Radial grading {grading:.4g} (cell-to-cell ratio {cell_ratio:.3f}) clusters cells at the wall.
scale   1;

vertices
(
{chr(10).join(vertices)}
);

blocks
(
{chr(10).join(blocks)}
);

edges
(
{chr(10).join(edges)}
);

boundary
(
    {inlet}
    {{
        type patch;
        faces
        (
{chr(10).join(inlet_faces)}
        );
    }}

    {outlet}
    {{
        type patch;
        faces
        (
{chr(10).join(outlet_faces)}
        );
    }}

    {wall}
    {{
        type wall;
        faces
        (
{chr(10).join(wall_faces)}
        );
    }}
);
"""


def _bend_block_mesh(mesh: MeshSpec, inlet: str, outlet: str, wall: str) -> str:
    """Swept O-grid elbow with a straight lead-in and lead-out.

    The bend is the canonical local geometry for flow-accelerated corrosion and
    erosion: the outer wall carries the wall-shear peak that a one-dimensional
    model replaces with a textbook multiplier. The cross-section is swept along
    the centreline arc, so every longitudinal edge is a true circular arc about
    the bend axis and the mesh follows the curvature exactly.
    """
    radius = mesh.diameter_m / 2.0
    core_radius = mesh.core_fraction * radius
    bend_radius = mesh.bend_radius_m
    sweep = radians(mesh.bend_angle_deg)
    angles = [radians(45.0 + 90.0 * k) for k in range(4)]

    # Centreline frame: e1 stays out of plane, e2 = t x e1, t = dc/dphi.
    def frame(phi: float):
        centre = (bend_radius * sin(phi), 0.0, bend_radius * (1.0 - cos(phi)))
        tangent = (cos(phi), 0.0, sin(phi))
        return centre, tangent, (0.0, 1.0, 0.0), (-sin(phi), 0.0, cos(phi))

    def offset(base, direction, distance):
        return tuple(base[i] + direction[i] * distance for i in range(3))

    def ring(centre, e1, e2, r):
        points = []
        for angle in angles:
            points.append(
                tuple(
                    centre[i] + r * (cos(angle) * e1[i] + sin(angle) * e2[i]) for i in range(3)
                )
            )
        return points

    start_centre, start_tangent, e1_start, e2_start = frame(0.0)
    end_centre, end_tangent, e1_end, e2_end = frame(sweep)
    mid_centre, _, e1_mid, e2_mid = frame(0.5 * sweep)

    stations = [
        (offset(start_centre, start_tangent, -mesh.inlet_length_m), e1_start, e2_start),
        (start_centre, e1_start, e2_start),
        (end_centre, e1_end, e2_end),
        (offset(end_centre, end_tangent, mesh.outlet_length_m), e1_end, e2_end),
    ]

    vertices: list[str] = []
    for centre, e1, e2 in stations:
        for point in ring(centre, e1, e2, core_radius):
            vertices.append("    ({:.8g} {:.8g} {:.8g})".format(*point))
        for point in ring(centre, e1, e2, radius):
            vertices.append("    ({:.8g} {:.8g} {:.8g})".format(*point))

    grading, cell_ratio = _wall_grading(
        radius - core_radius, mesh.radial_cells, mesh.first_cell_height_m
    )

    arc_length = bend_radius * sweep
    bend_cells = max(4, mesh.axial_cells)
    inlet_cells = max(4, round(bend_cells * mesh.inlet_length_m / arc_length))
    outlet_cells = max(4, round(bend_cells * mesh.outlet_length_m / arc_length))
    segment_cells = [inlet_cells, bend_cells, outlet_cells]

    blocks: list[str] = []
    edges: list[str] = []
    wall_faces: list[str] = []

    for segment in range(3):
        base = 8 * segment
        far = base + 8
        cells = segment_cells[segment]
        blocks.append(
            f"    hex ({base} {base + 1} {base + 2} {base + 3} "
            f"{far} {far + 1} {far + 2} {far + 3}) "
            f"({mesh.tangential_cells} {mesh.tangential_cells} {cells}) simpleGrading (1 1 1)"
        )
        for k in range(4):
            nxt = (k + 1) % 4
            o0, o1 = base + 4 + k, base + 4 + nxt
            i0, i1 = base + k, base + nxt
            blocks.append(
                f"    hex ({o0} {o1} {i1} {i0} {o0 + 8} {o1 + 8} {i1 + 8} {i0 + 8}) "
                f"({mesh.tangential_cells} {mesh.radial_cells} {cells}) "
                f"simpleGrading (1 {grading:.6g} 1)"
            )
            wall_faces.append(f"        ({o0} {o1} {o1 + 8} {o0 + 8})")

    # Cross-section arcs on the outer circle at every station.
    for station, (centre, e1, e2) in enumerate(stations):
        base = 8 * station
        for k in range(4):
            nxt = (k + 1) % 4
            mid = radians(90.0 + 90.0 * k)
            point = tuple(
                centre[i] + radius * (cos(mid) * e1[i] + sin(mid) * e2[i]) for i in range(3)
            )
            edges.append(
                "    arc {} {} ({:.8g} {:.8g} {:.8g})".format(
                    base + 4 + k, base + 4 + nxt, *point
                )
            )

    # Longitudinal edges through the bend are arcs about the bend axis.
    for k in range(4):
        for local, r in ((k, core_radius), (4 + k, radius)):
            point = tuple(
                mid_centre[i] + r * (cos(angles[k]) * e1_mid[i] + sin(angles[k]) * e2_mid[i])
                for i in range(3)
            )
            edges.append(
                "    arc {} {} ({:.8g} {:.8g} {:.8g})".format(8 + local, 16 + local, *point)
            )

    inlet_faces = ["        (3 2 1 0)"]
    outlet_faces = ["        (24 25 26 27)"]
    for k in range(4):
        nxt = (k + 1) % 4
        inlet_faces.append(f"        ({k} {nxt} {4 + nxt} {4 + k})")
        outlet_faces.append(f"        ({28 + k} {28 + nxt} {24 + nxt} {24 + k})")

    return f"""
// O-grid elbow: diameter {mesh.diameter_m:g} m, bend radius {bend_radius:g} m
// (R/D = {bend_radius / mesh.diameter_m:.2f}), sweep {mesh.bend_angle_deg:g} deg,
// lead-in {mesh.inlet_length_m:g} m, lead-out {mesh.outlet_length_m:g} m.
// Radial grading {grading:.4g} (cell-to-cell ratio {cell_ratio:.3f}) clusters cells at the wall.
scale   1;

vertices
(
{chr(10).join(vertices)}
);

blocks
(
{chr(10).join(blocks)}
);

edges
(
{chr(10).join(edges)}
);

boundary
(
    {inlet}
    {{
        type patch;
        faces
        (
{chr(10).join(inlet_faces)}
        );
    }}

    {outlet}
    {{
        type patch;
        faces
        (
{chr(10).join(outlet_faces)}
        );
    }}

    {wall}
    {{
        type wall;
        faces
        (
{chr(10).join(wall_faces)}
        );
    }}
);
"""


def _channel_block_mesh(mesh: MeshSpec, inlet: str, outlet: str, wall: str) -> str:
    """Single-block rectangular duct graded towards both wall pairs."""
    height = mesh.height_m
    width = mesh.width_m
    length = mesh.length_m
    half_cells = max(1, mesh.radial_cells // 2)
    grading, cell_ratio = _wall_grading(height / 2.0, half_cells, mesh.first_cell_height_m)
    symmetric = f"( (0.5 {half_cells} {grading:.6g}) (0.5 {half_cells} {1.0 / grading:.6g}) )"

    vertices = [
        "    (0 0 0)",
        f"    ({length:.8g} 0 0)",
        f"    ({length:.8g} {height:.8g} 0)",
        f"    (0 {height:.8g} 0)",
        f"    (0 0 {width:.8g})",
        f"    ({length:.8g} 0 {width:.8g})",
        f"    ({length:.8g} {height:.8g} {width:.8g})",
        f"    (0 {height:.8g} {width:.8g})",
    ]

    return f"""
// Rectangular duct {mesh.height_m:g} x {mesh.width_m:g} x {mesh.length_m:g} m.
// Wall-normal grading {grading:.4g} (cell-to-cell ratio {cell_ratio:.3f}) at both walls.
scale   1;

vertices
(
{chr(10).join(vertices)}
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({mesh.axial_cells} {2 * half_cells} {mesh.tangential_cells})
    simpleGrading (1 {symmetric} 1)
);

edges
(
);

boundary
(
    {inlet}
    {{
        type patch;
        faces ( (0 4 7 3) );
    }}

    {outlet}
    {{
        type patch;
        faces ( (1 2 6 5) );
    }}

    {wall}
    {{
        type wall;
        faces
        (
            (0 1 5 4)
            (3 7 6 2)
            (0 3 2 1)
            (4 5 6 7)
        );
    }}
);
"""


def _wall_grading(
    thickness: float, cells: int, first_cell_height: float | None
) -> tuple[float, float]:
    """Return the blockMesh expansion ratio and the underlying per-cell ratio.

    ``simpleGrading`` takes the ratio of the last cell to the first cell, so the
    per-cell geometric ratio is solved first and then raised to ``cells - 1``. The
    per-cell ratio is returned too, because it - not the blockMesh value - decides
    whether the mesh is acceptable.
    """
    if first_cell_height is None or cells < 2:
        return 1.0, 1.0
    if first_cell_height <= 0.0 or first_cell_height * cells >= thickness:
        return 1.0, 1.0

    def total(ratio: float) -> float:
        return first_cell_height * (ratio**cells - 1.0) / (ratio - 1.0)

    low, high = 1.0 + 1.0e-9, 5.0
    while total(high) < thickness and high < 1.0e3:
        high *= 2.0
    for _ in range(200):
        middle = 0.5 * (low + high)
        if total(middle) < thickness:
            low = middle
        else:
            high = middle
    cell_ratio = 0.5 * (low + high)
    return cell_ratio ** (cells - 1), cell_ratio


def _cells_for_ratio(thickness: float, first_cell_height: float) -> int:
    """Smallest cell count that spans ``thickness`` within the accepted expansion."""
    cells = 2
    while cells < 500:
        covered = (
            first_cell_height
            * (_MAX_CELL_EXPANSION**cells - 1.0)
            / (_MAX_CELL_EXPANSION - 1.0)
        )
        if covered >= thickness:
            return cells
        cells += 1
    return cells


# ------------------------------------------------------------------- execution


def detect_openfoam(*, bashrc: str | None = None) -> str | None:
    """Return how OpenFOAM can be reached, or ``None`` when it is unavailable.

    The returned value is either ``"path"`` when the solvers are already on PATH,
    or the path to an ``etc/bashrc`` that must be sourced first.
    """
    candidate = bashrc or os.environ.get("OPENFOAM_BASHRC") or os.environ.get("FOAM_BASHRC")
    if candidate and Path(candidate).is_file():
        return str(candidate)
    if shutil.which("blockMesh"):
        return "path"
    for pattern in ("opt/openfoam*/etc/bashrc", "usr/lib/openfoam/openfoam*/etc/bashrc"):
        matches = sorted(Path("/").glob(pattern))
        if matches:
            return str(matches[-1])
    return None


def _run_foam_command(
    command: str, case_dir: Path, environment: str, timeout_seconds: int
) -> RunStep:
    if environment == "path":
        argv: list[str] = shlex.split(command)
    else:
        argv = ["bash", "-lc", f"source {shlex.quote(environment)} >/dev/null 2>&1 && {command}"]

    try:
        completed = subprocess.run(  # noqa: S603 - commands come from a fixed set
            argv,
            cwd=str(case_dir),
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
        )
    except (OSError, subprocess.SubprocessError) as error:
        return RunStep(command=command, returncode=None, stdout_tail="", stderr_tail=str(error))

    return RunStep(
        command=command,
        returncode=completed.returncode,
        stdout_tail=_tail(completed.stdout),
        stderr_tail=_tail(completed.stderr),
    )


def _tail(text: str, lines: int = 25) -> str:
    return "\n".join((text or "").strip().splitlines()[-lines:])


# ----------------------------------------------------------------- results I/O


def read_case_results(
    case_dir: str | Path, *, density_kg_per_m3: float | None = None
) -> OpenFoamResults:
    """Read the function-object output of a solved case into engineering numbers.

    Incompressible OpenFOAM reports kinematic pressure and kinematic wall shear
    (m2/s2). When ``density_kg_per_m3`` is supplied they are converted to Pa, which
    is what a receiving corrosion, erosion or pressure-drop model expects. A volume
    of fluid case already reports ``p_rgh`` in Pa, so leave the density out for it.
    """
    root = Path(case_dir) / "postProcessing"
    findings: list[str] = []

    if not root.is_dir():
        return OpenFoamResults(
            None, None, None, None, None, None, None, None, None, None,
            ("No postProcessing directory; the case has not produced results yet.",),
        )

    inlet_flux = _scalar_result(root, "inletFlux")
    outlet_flux = _scalar_result(root, "outletFlux")
    inlet_pressure = _scalar_result(root, "inletPressure")
    outlet_pressure = _scalar_result(root, "outletPressure")
    peak_shear = _magnitude_result(root, prefix="peakWallShear")
    mean_shear = _magnitude_result(root, prefix="meanWallShear")
    dispersed_fraction = _scalar_result(root, "outletDispersedFraction")
    y_plus = _y_plus_result(root)

    continuity = None
    inlet_volumetric = abs(inlet_flux) if inlet_flux is not None else None
    outlet_volumetric = abs(outlet_flux) if outlet_flux is not None else None
    if inlet_volumetric and outlet_volumetric:
        continuity = abs(outlet_volumetric - inlet_volumetric) / inlet_volumetric
        if continuity > 0.01:
            findings.append(
                f"Inlet and outlet volumetric flow differ by {100.0 * continuity:.2f} %; "
                "the solution is not converged on continuity."
            )

    pressure_drop = None
    if inlet_pressure is not None and outlet_pressure is not None:
        pressure_drop = inlet_pressure - outlet_pressure
        if density_kg_per_m3:
            pressure_drop *= density_kg_per_m3
        else:
            findings.append(
                "Pressure drop is reported as read; supply density_kg_per_m3 to convert "
                "a kinematic (m2/s2) incompressible pressure to Pa."
            )

    if density_kg_per_m3:
        peak_shear = peak_shear * density_kg_per_m3 if peak_shear is not None else None
        mean_shear = mean_shear * density_kg_per_m3 if mean_shear is not None else None
    elif peak_shear is not None:
        findings.append("Wall shear is kinematic (m2/s2); supply density_kg_per_m3 to obtain Pa.")

    if y_plus:
        findings.append(
            f"Wall resolution: y+ min {y_plus[0]:.2f}, mean {y_plus[1]:.2f}, max {y_plus[2]:.2f}. "
            "Feed these into the quality gate before using any local value."
        )
    if dispersed_fraction is not None:
        findings.append(
            f"Outlet dispersed-phase fraction {dispersed_fraction:.4g}; compare it with the "
            "inlet flash split to judge whether the phases separated in the geometry."
        )

    return OpenFoamResults(
        inlet_volumetric_flow_m3_per_s=inlet_volumetric,
        outlet_volumetric_flow_m3_per_s=outlet_volumetric,
        continuity_error_relative=continuity,
        pressure_drop_pa=pressure_drop,
        peak_wall_shear_pa=peak_shear,
        mean_wall_shear_pa=mean_shear,
        y_plus_min=y_plus[0] if y_plus else None,
        y_plus_mean=y_plus[1] if y_plus else None,
        y_plus_max=y_plus[2] if y_plus else None,
        outlet_dispersed_fraction=dispersed_fraction,
        findings=tuple(findings),
    )


def _latest_data_file(root: Path, name: str, filename: str) -> Path | None:
    directory = root / name
    if not directory.is_dir():
        return None
    candidates = sorted(
        (path for path in directory.glob(f"*/{filename}") if path.is_file()),
        key=lambda path: _time_key(path.parent.name),
    )
    return candidates[-1] if candidates else None


def _time_key(name: str) -> float:
    try:
        return float(name)
    except ValueError:
        return -1.0


def _last_row(path: Path) -> list[str] | None:
    rows = [
        line.strip()
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    if not rows:
        return None
    return _tokenise(rows[-1])


def _tokenise(row: str) -> list[str]:
    """Split a data row, keeping parenthesised vectors as single tokens."""
    return re.findall(r"\([^)]*\)|\S+", row)


def _scalar_result(root: Path, name: str) -> float | None:
    path = _latest_data_file(root, name, "surfaceFieldValue.dat")
    if path is None:
        return None
    tokens = _last_row(path)
    if not tokens or len(tokens) < 2:
        return None
    return _as_magnitude(tokens[-1])


def _magnitude_result(root: Path, *, prefix: str) -> float | None:
    values = []
    for directory in sorted(root.glob(f"{prefix}*")):
        path = _latest_data_file(root, directory.name, "surfaceFieldValue.dat")
        if path is None:
            continue
        tokens = _last_row(path)
        if tokens and len(tokens) >= 2:
            value = _as_magnitude(tokens[-1])
            if value is not None:
                values.append(value)
    return max(values) if values else None


def _y_plus_result(root: Path) -> tuple[float, float, float] | None:
    path = _latest_data_file(root, "yPlus", "yPlus.dat")
    if path is None:
        return None
    minima: list[float] = []
    maxima: list[float] = []
    averages: list[float] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        tokens = line.split()
        if len(tokens) < 5:
            continue
        try:
            minima.append(float(tokens[-3]))
            maxima.append(float(tokens[-2]))
            averages.append(float(tokens[-1]))
        except ValueError:
            continue
    if not minima:
        return None
    return min(minima), sum(averages) / len(averages), max(maxima)


def _as_magnitude(token: str) -> float | None:
    if token.startswith("("):
        try:
            components = [float(part) for part in token.strip("()").split()]
        except ValueError:
            return None
        return sum(component**2 for component in components) ** 0.5
    try:
        value = float(token)
    except ValueError:
        return None
    return value if isfinite(value) else None


def _foam_file(class_name: str, location: str, object_name: str) -> str:
    return _HEADER.format(class_name=class_name, location=location, object_name=object_name)


def _foam_name(phase: str) -> str:
    """OpenFOAM phase names appear in field names, so keep them alphanumeric."""
    cleaned = re.sub(r"[^0-9a-zA-Z]+", "", phase or "")
    return cleaned or "phase"


def _nu_entry(spec: dict[str, Any], nu: float) -> str:
    if spec["dimensioned_nu"]:
        return f"nu              [0 2 -1 0 0 0 0] {nu:.8g};"
    return f"nu              {nu:.8g};"


def _require_positive(name: str, value: float | None) -> None:
    if value is None or not isfinite(value) or value <= 0.0:
        raise ValueError(f"{name} must be a positive finite number")
