"""Public, screening-level reservoir model set-up from limited data."""

from .builder import (
    DATA_TIERS,
    RefinementItem,
    ReservoirInputs,
    ReservoirModel,
    ReservoirModelBuilder,
    Volumetrics,
    build_reservoir_model,
    summarize,
)
from .data_first import (
    ATTEMPT_OUTCOMES,
    DATA_LADDER,
    acquisition_plan,
    best_available,
    data_first_gate,
    rank_of,
)
from .parameters import (
    AQUIFER_VOLUME_MULTIPLE,
    GENERIC_DEFAULTS,
    PARAMETER_WEIGHTS,
    RECOVERY_FACTOR,
    Parameter,
)
from .static_model import (
    GRID_KEYWORDS,
    KEYWORD_BOUNDS,
    REGION_KEYWORDS,
    REQUIRED_KEYWORDS,
    SILENT_FAILURE_MODES,
    GridDimensions,
    StaticModelArrays,
    build_static_model_deck_input,
    derive_permz,
    rebase_regions,
    reconcile_volume,
    static_model_checklist,
    validate_array,
    write_keyword_include,
)
from .structure import (
    SEA_AREA_DEFAULT_PLAY,
    STRATIGRAPHY,
    STRUCTURAL_STYLE,
    StructuralAssumption,
    StructuralModel,
    assume_structure,
    assumption_register,
    longest_run_above_contact,
    resolve_play,
    solve_amplitude_for_split,
    solve_contact_for_volume,
)

__all__ = [
    "acquisition_plan",
    "AQUIFER_VOLUME_MULTIPLE",
    "ATTEMPT_OUTCOMES",
    "best_available",
    "DATA_LADDER",
    "data_first_gate",
    "DATA_TIERS",
    "GENERIC_DEFAULTS",
    "GRID_KEYWORDS",
    "GridDimensions",
    "KEYWORD_BOUNDS",
    "PARAMETER_WEIGHTS",
    "Parameter",
    "rank_of",
    "RECOVERY_FACTOR",
    "REGION_KEYWORDS",
    "REQUIRED_KEYWORDS",
    "RefinementItem",
    "ReservoirInputs",
    "ReservoirModel",
    "ReservoirModelBuilder",
    "SEA_AREA_DEFAULT_PLAY",
    "SILENT_FAILURE_MODES",
    "STRATIGRAPHY",
    "STRUCTURAL_STYLE",
    "StaticModelArrays",
    "StructuralAssumption",
    "StructuralModel",
    "Volumetrics",
    "assume_structure",
    "assumption_register",
    "build_reservoir_model",
    "build_static_model_deck_input",
    "derive_permz",
    "longest_run_above_contact",
    "rebase_regions",
    "reconcile_volume",
    "resolve_play",
    "solve_amplitude_for_split",
    "solve_contact_for_volume",
    "static_model_checklist",
    "summarize",
    "validate_array",
    "write_keyword_include",
]

__version__ = "0.2.0"
